[tool.cibuildwheel]
build = "cp3*"
skip = ["cp36-*", "cp37-*", "*-win32", "*-manylinux_i686", "*-musllinux_*"]
build-verbosity = 1
before-build = "rm -rf {package}/osqp_sources/build"
repair-wheel-command = ""

[tool.cibuildwheel.linux]
before-all = [
  "yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo",
  "yum search cuda-toolkit*",
  "yum install -y cuda-toolkit-13-0"
]
environment = { CMAKE_CUDA_COMPILER = "/usr/local/cuda-13.0/bin/nvcc" }
